/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Naufal Zayn M
 */
public class viewInterface extends javax.swing.JFrame {

    /**
     * Creates new form viewInterface
     */
    public viewInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        awal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        halamanUtama = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        donasi = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        peta = new javax.swing.JLabel();
        ancaman = new javax.swing.JLabel();
        konservasi = new javax.swing.JLabel();
        utama = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        donation = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        petauhuy = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        wilayah = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        terancam = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        awal.setBackground(new java.awt.Color(223, 218, 186));
        awal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/RUSA.png"))); // NOI18N
        awal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Above DEMO", 0, 24)); // NOI18N
        jLabel6.setText("save them");
        awal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/login 1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        awal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel8.setText("login");
        awal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 70, -1));

        getContentPane().add(awal, "card2");

        login.setBackground(new java.awt.Color(223, 218, 186));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/login 3.png"))); // NOI18N
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Above DEMO", 0, 24)); // NOI18N
        jLabel3.setText("login");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 290, 10));

        jLabel4.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel4.setText("password");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 20));
        login.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 150, -1));

        jLabel5.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel5.setText("username");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 20));
        login.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 150, -1));

        jLabel9.setFont(new java.awt.Font("Above DEMO", 0, 14)); // NOI18N
        jLabel9.setText("register");
        login.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/register 1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        login.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/login 1.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        login.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        getContentPane().add(login, "card3");

        register.setBackground(new java.awt.Color(223, 218, 186));
        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Above DEMO", 0, 24)); // NOI18N
        jLabel12.setText("register");
        register.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/register 3.png"))); // NOI18N
        register.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        register.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 340, 10));

        jLabel14.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel14.setText("username");
        register.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, 20));
        register.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 150, -1));

        jLabel15.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel15.setText("password");
        register.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 20));
        register.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 150, -1));

        jLabel16.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel16.setText("email");
        register.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 20));
        register.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 150, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mantap.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        register.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jLabel18.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel18.setText("mantap!");
        register.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        getContentPane().add(register, "card4");

        halamanUtama.setBackground(new java.awt.Color(223, 218, 186));
        halamanUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/about.png"))); // NOI18N
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        halamanUtama.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        donasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/donasi.png"))); // NOI18N
        donasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donasiMouseClicked(evt);
            }
        });
        halamanUtama.add(donasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        halamanUtama.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        peta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/peta.png"))); // NOI18N
        peta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petaMouseClicked(evt);
            }
        });
        halamanUtama.add(peta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        ancaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/terancam.png"))); // NOI18N
        ancaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ancamanMouseClicked(evt);
            }
        });
        halamanUtama.add(ancaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        konservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/konservasi.png"))); // NOI18N
        konservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konservasiMouseClicked(evt);
            }
        });
        halamanUtama.add(konservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        utama.setBackground(new java.awt.Color(223, 218, 186));
        utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Above DEMO", 0, 36)); // NOI18N
        jLabel29.setText("halaman utama");
        utama.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        halamanUtama.add(utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 270));

        donation.setBackground(new java.awt.Color(217, 107, 70));

        jLabel28.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel28.setText("donasi");
        donation.add(jLabel28);

        halamanUtama.add(donation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 270));

        petauhuy.setBackground(new java.awt.Color(223, 218, 186));

        jLabel27.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel27.setText("peta");
        petauhuy.add(jLabel27);

        halamanUtama.add(petauhuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 270));

        wilayah.setBackground(new java.awt.Color(151, 182, 203));

        jLabel25.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("apa itu kawasan konservasi");
        wilayah.add(jLabel25);

        halamanUtama.add(wilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 270));

        terancam.setBackground(new java.awt.Color(5, 102, 151));

        jLabel26.setFont(new java.awt.Font("Above DEMO", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("kenapa mereka terancam punah?");
        terancam.add(jLabel26);

        halamanUtama.add(terancam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 270));

        getContentPane().add(halamanUtama, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        awal.setVisible(false);
        login.setVisible(true);
                
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        login.setVisible(false);
        register.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        register.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        login.setVisible(false);
        halamanUtama.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void ancamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ancamanMouseClicked
        // TODO add your handling code here:
        utama.removeAll();
        utama.repaint();
        utama.revalidate();
        
        utama.add(terancam);
        utama.repaint();
        utama.revalidate();
    }//GEN-LAST:event_ancamanMouseClicked

    private void konservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konservasiMouseClicked
        // TODO add your handling code here:
        utama.removeAll();
        utama.repaint();
        utama.revalidate();
        
        utama.add(wilayah);
        utama.repaint();
        utama.revalidate();
    }//GEN-LAST:event_konservasiMouseClicked

    private void petaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petaMouseClicked
        // TODO add your handling code here:
        utama.removeAll();
        utama.repaint();
        utama.revalidate();
        
        utama.add(petauhuy);
        utama.repaint();
        utama.revalidate();
    }//GEN-LAST:event_petaMouseClicked

    private void donasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donasiMouseClicked
        // TODO add your handling code here:
        utama.removeAll();
        utama.repaint();
        utama.revalidate();
        
        utama.add(donation);
        utama.repaint();
        utama.revalidate();
    }//GEN-LAST:event_donasiMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        halamanUtama.setVisible(false);
        awal.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        about a=new about();
        a.setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel ancaman;
    private javax.swing.JPanel awal;
    private javax.swing.JLabel donasi;
    private javax.swing.JPanel donation;
    private javax.swing.JPanel halamanUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel konservasi;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel peta;
    private javax.swing.JPanel petauhuy;
    private javax.swing.JPanel register;
    private javax.swing.JPanel terancam;
    private javax.swing.JPanel utama;
    private javax.swing.JPanel wilayah;
    // End of variables declaration//GEN-END:variables
}
